package com.messenger.protocol;

public enum PacketType {
    LOGIN_REQUEST,
    LOGIN_RESPONSE,
    REGISTER_REQUEST,
    REGISTER_RESPONSE,

    SEND_MESSAGE,
    MESSAGE_BROADCAST,
    CHANNEL_HISTORY,

    JOIN_CHANNEL,
    LEAVE_CHANNEL,
    GET_SERVERS,
    SERVERS_LIST,
    GET_CHANNELS,
    CHANNELS_LIST,
    CREATE_SERVER,
    CREATE_CHANNEL,
    JOIN_SERVER,
    GET_MEMBERS,
    MEMBERS_LIST,

    FILE_UPLOAD,
    FILE_DOWNLOAD,
    FILE_DATA,

    DISCONNECT,
    ERROR,
    PING,
    EVENT, COMMAND_RESPONSE, COMMAND, PONG
}